src/Clinic.Domain/Entities/Education.cs
=> Add Education model

src/Clinic.Domain/Entities/Doctor.cs
=> Add doctor model

src/Clinic.Domain/Entities/New.cs
=> add new models

src/Clinic.Domain/Entities/Result.cs
=> Add result model

src/Clinic.Domain/Entities/Skill.cs
=> adding skill models

src/Clinic.Domain/Entities/Feedback.cs
=> add feedbackmodel

src/Clinic.Domain/Entities/Service.cs
=> adding Service model

src/Clinic.Domain/Entities/Diplom.cs
=> Add-Dipliom-Model

src/Clinic.Domain/Entities/Result.cs
=> result to'ldirildi

src/Clinic.Domain/Entities/Specialist.cs
=> Add-Specialist-Model

src/Clinic.Application/Clinic.Application.csproj
=> GetReady-UseCases

src/Clinic.Application/Abstractions/IClinincDbContext.cs, src/Clinic.Application/Clinic.Application.csproj
=> Add-Abstraction

src/Clinic.Application/Abstractions/IClinincDbContext.cs
Savechanges qolib ketibdi (qoshildi)
=> Abu pro/add abstractions

src/Clinic.Infrastructure/Clinic.Infrastructure.csproj, src/Clinic.Infrastructure/Persistance/ClinincDbContext.cs
=> Add-Persistance

src/Clinic.API/Clinic.API.csproj, src/Clinic.Application/Abstractions/IClinincDbContext.cs, src/Clinic.Application/Clinic.Application.csproj, src/Clinic.Application/UseCases/Diploms/Commands/CreateDiplomCommand.cs, src/Clinic.Application/UseCases/Diploms/Commands/DeleteDiplomCommand.cs, src/Clinic.Application/UseCases/Diploms/Commands/UpdateDiplomCommand.cs, src/Clinic.Application/UseCases/Diploms/Handlers/CommandHandlers/CreateDiplomCommandHandler.cs, src/Clinic.Application/UseCases/Diploms/Handlers/CommandHandlers/DeleteDiplomCommandHandler.cs, src/Clinic.Application/UseCases/Diploms/Handlers/CommandHandlers/UpdateDiplomCommandHander.cs, src/Clinic.Application/UseCases/Diploms/Handlers/QueryHandlers/GetAllDiplomsQueryHandler.cs, src/Clinic.Application/UseCases/Diploms/Handlers/QueryHandlers/GetDiplomByIdQueryHandler.cs, src/Clinic.Application/UseCases/Diploms/Quries/GetAllDiplomsQuery.cs, src/Clinic.Application/UseCases/Diploms/Quries/GetDiplomByIdQuery.cs, src/Clinic.Domain/DTOs/ResponseModel.cs, src/Clinic.Domain/Entities/Diplom.cs, src/Clinic.Infrastructure/Persistance/ClinincDbContext.cs
=> Add Diplom CRUD

src/Clinic.API/appsettings.json, src/Clinic.Application/Abstractions/IClinincDbContext.cs, src/Clinic.Infrastructure/Clinic.Infrastructure.csproj, src/Clinic.Infrastructure/ClinicInfrastructureDdependencyInjection.cs, src/Clinic.Infrastructure/Persistance/ClinincDbContext.cs
=> Add Infrastructure Dependency Injectopn

src/Clinic.Application/UseCases/Services/Commands/CreateServiceCommand.cs, src/Clinic.Application/UseCases/Services/Commands/DeleteServiceCommand.cs, src/Clinic.Application/UseCases/Services/Commands/UpdateServiceCommand.cs, src/Clinic.Application/UseCases/Services/Handlers/CommandHandlers/CreateServiceCommandHandler.cs, src/Clinic.Application/UseCases/Services/Handlers/CommandHandlers/DeleteServiceCommandHandler.cs, src/Clinic.Application/UseCases/Services/Handlers/CommandHandlers/UpdateServiceCommandHandler.cs, src/Clinic.Application/UseCases/Services/Handlers/QueryHandlers/GetAllServicesQueryHandler.cs, src/Clinic.Application/UseCases/Services/Handlers/QueryHandlers/GetByIdQueryHandler.cs, src/Clinic.Application/UseCases/Services/Queries/GetAllServicesQuery.cs, src/Clinic.Application/UseCases/Services/Queries/GetByIdServiceQuery.cs, src/Clinic.Domain/Entities/Service.cs
=> Add-Service-CRUD

src/Clinic.Application/UseCases/Educations/Commands/CreateEducationCommand.cs, src/Clinic.Application/UseCases/Educations/Commands/DeleteEducationCommand.cs, src/Clinic.Application/UseCases/Educations/Commands/UpdateEducationCommand.cs, src/Clinic.Application/UseCases/Educations/Handlers/CommandHandlers/CreateEducationCommandHandler.cs, src/Clinic.Application/UseCases/Educations/Handlers/CommandHandlers/DeleteEducationCommandHandler.cs, src/Clinic.Application/UseCases/Educations/Handlers/CommandHandlers/UpdateEducationCommandHandler.cs, src/Clinic.Application/UseCases/Educations/Handlers/QueryHandlers/GetAllEducationsQueryHandler.cs, src/Clinic.Application/UseCases/Educations/Handlers/QueryHandlers/GetEducationByIdQueryHandler.cs, src/Clinic.Application/UseCases/Educations/Queries/GetAllEducationsQuery.cs, src/Clinic.Application/UseCases/Educations/Queries/GetEducationByIdQuery.cs
=> add Education CRUD

src/Clinic.Application/UseCases/News/Commands/CreateNewsCommand.cs, src/Clinic.Application/UseCases/News/Commands/DeleteNewsCommand.cs, src/Clinic.Application/UseCases/News/Commands/UpdateNewsCommand.cs, src/Clinic.Application/UseCases/News/Handlers/CommandHandlers/CreateNewsCommandHandler.cs, src/Clinic.Application/UseCases/News/Handlers/CommandHandlers/DeleteNewsCommandHandler.cs, src/Clinic.Application/UseCases/News/Handlers/CommandHandlers/UpdateNewsCommandHandler.cs, src/Clinic.Application/UseCases/News/Handlers/QueryHandlers/GetAllNewsQueryHandler.cs, src/Clinic.Application/UseCases/News/Handlers/QueryHandlers/GetNewsByIdQueryHandler.cs, src/Clinic.Application/UseCases/News/Queries/GetAllNewsQuery.cs, src/Clinic.Application/UseCases/News/Queries/GetNewsByIdQuery.cs
=> Add-New-CRUD

src/Clinic.Application/UseCases/Diploms/Handlers/QueryHandlers/GetAllDiplomsQueryHandler.cs, src/Clinic.Application/UseCases/Diploms/Quries/GetAllDiplomsQuery.cs, src/Clinic.Application/UseCases/Educations/Handlers/QueryHandlers/GetAllEducationsQueryHandler.cs, src/Clinic.Application/UseCases/Educations/Queries/GetAllEducationsQuery.cs, src/Clinic.Application/UseCases/Services/Handlers/QueryHandlers/GetAllServicesQueryHandler.cs, src/Clinic.Application/UseCases/Services/Queries/GetAllServicesQuery.cs, src/Clinic.Application/UseCases/Skills/Hendlers/QueryHnadlers/GetAllSkillsQueryHandler.cs, src/Clinic.Application/UseCases/Skills/Quries/GetAllSkillsQuery.cs
=> Change-Getall-ToPageantionStyle

src/Clinic.API/Program.cs, src/Clinic.API/appsettings.json, src/Clinic.Application/Clinic.Application.csproj, src/Clinic.Application/UseCases/AuthService/AuthService.cs, src/Clinic.Application/UseCases/AuthService/IAuthService.cs, src/Clinic.Domain/Entities/Auth/User.cs
=> Add-Auth-Service

src/Clinic.API/Program.cs, src/Clinic.Application/UseCases/AuthService/AuthService.cs
=> Add Token Bucket middleware

src/Clinic.Application/Clinic.Application.csproj, src/Clinic.Application/UseCases/Diploms/Commands/CreateDiplomCommand.cs, src/Clinic.Application/UseCases/Results/Commands/CreateResultCommand.cs, src/Clinic.Application/UseCases/Results/Commands/DeleteResultCommand.cs, src/Clinic.Application/UseCases/Results/Commands/UpdateResultCommand.cs, src/Clinic.Application/UseCases/Results/Handlers/CommandHandlers/CreateResultCommandHandler.cs, src/Clinic.Application/UseCases/Results/Handlers/CommandHandlers/DeleteResultCommandHandler.cs, src/Clinic.Application/UseCases/Results/Handlers/CommandHandlers/UpdateResultCommandHandler.cs, src/Clinic.Application/UseCases/Results/Handlers/QueryHandlers/GetAllResultsQueryHandler.cs, src/Clinic.Application/UseCases/Results/Handlers/QueryHandlers/GetResultByIdQueryhandler.cs
=> Result CRUD

src/Clinic.API/Controllers/SpecialistController.cs, src/Clinic.Application/UseCases/Specialists/Handlers/QueryHandlers/GetAllSpecialistsQueryHandler.cs, src/Clinic.Application/UseCases/Specialists/Queries/GetAllSpecialistsQuery.cs
=> Add-Specialist-Controller

src/Clinic.API/Controllers/SkillsController.cs
=> Add-Skills-Controller

src/Clinic.API/Controllers/ResultController.cs, src/Clinic.Application/Clinic.Application.csproj, src/Clinic.Application/UseCases/Results/Handlers/QueryHandlers/GetAllResultsQueryHandler.cs, src/Clinic.Application/UseCases/Results/Handlers/QueryHandlers/GetResultByIdQueryhandler.cs, src/Clinic.Application/UseCases/Results/Queries/GetAllResultsQuery.cs, src/Clinic.Application/UseCases/Results/Queries/GetResultByIdQuery.cs
=> Add-Result-Controller

src/Clinic.API/Controllers/EducationController.cs
=> Add-Education-Controller

src/Clinic.API/Controllers/FeedBackController.cs, src/Clinic.API/Controllers/NewController.cs
=> Add-News-Controller

src/Clinic.API/Controllers/ServiceTypeController.cs
=> Add-ServiceType-Controller

src/Clinic.API/Controllers/AuthController.cs, src/Clinic.API/Controllers/LeoginDTO.cs, src/Clinic.API/Controllers/ResultController.cs, src/Clinic.API/Controllers/ServiceController.cs, src/Clinic.API/Controllers/ServiceTypeController.cs, src/Clinic.API/Program.cs
=> Add seeed data and some changes

src/Clinic.Application/UseCases/Doctors/Commands/CreateDoctorCommand.cs, src/Clinic.Application/UseCases/Doctors/Commands/DeleteDoctorCommand.cs, src/Clinic.Application/UseCases/Doctors/Commands/UpdateDoctorCommand.cs, src/Clinic.Application/UseCases/Doctors/Handlers/CommandHandlers/CreateDoctorCommandHandler.cs, src/Clinic.Application/UseCases/Doctors/Handlers/CommandHandlers/DeleteDoctorCommandHandler.cs, src/Clinic.Application/UseCases/Doctors/Handlers/CommandHandlers/UpdateDoctorCommandHandler.cs, src/Clinic.Application/UseCases/Doctors/Handlers/QueryHandlers/GetAllDoctorsQueryHandler.cs, src/Clinic.Application/UseCases/Doctors/Handlers/QueryHandlers/GetDoctorByIdQueryHandler.cs, src/Clinic.Application/UseCases/Doctors/Queries/GetAllDoctorsQuery.cs, src/Clinic.Application/UseCases/Doctors/Queries/GetDoctorByIdQuery.cs
=> Add-Doctor-CRUD

src/Clinic.API/Controllers/DoctorController.cs
=> Add-Doctor-Controller
